### ISSUE TITLE
unique_on when all parameters are non unique

### ISSUE THREAD

**Issue by rainerz1964** [steinitzu/celery-singleton#23] opened 2020-07-21 11:30 UTC
I have a task

```
@app.task(bind=True, base=Singleton)
def do_something(self, otherarg=None):
    time.sleep(5)

```

I would like the otherarg to be not significant in the sense of task uniqueness. How do I express this by using 
`unique_on`. The option `unique_on=[]` didn't work

**Comment by steinitzu** [comment] 2020-07-21 17:22
This is a duplicate of https://github.com/steinitzu/celery-singleton/issues/15  
Until this is implemented, as a workaround you can add a dummy argument that never changes, e.g.:

```python3
@app.task(bind=True, base=Singleton, unique_on=['dummy'])
def do_something(self, otherarg=None, dummy=1):
    time.sleep(5)
```

**Closed by steinitzu** 2020-07-21 17:22 UTC
Labels: duplicate
